CREATE TABLE Tickets (
  ticketId INT AUTO_INCREMENT PRIMARY KEY,
  ticketNumber VARCHAR(10) NOT NULL,
  available BOOLEAN DEFAULT TRUE,
  name VARCHAR(255) DEFAULT NULL,
  phoneNumber VARCHAR(255) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  reservationDate TIMESTAMP DEFAULT NULL
);
